#!/bin/sh

RETVAL=

for x in `whereis -b -B /bin /usr/bin /usr/local/bin -f python`; do
    if [ "$x" == "python:" ]; then
	continue
    fi
    if [ "`$x -c \"import sys; print sys.version_info[0]\" 2> /dev/null`" == "2" ]; then
	RETVAL="$x"
	break
    fi
done

echo $RETVAL
